# Generated by Django 5.2.8 on 2025-11-24 02:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APICallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        choices=[
                            ("docker_repos", "Docker Repositories"),
                            ("docker_tags", "Docker Tags"),
                            ("ai_chat", "AI Chat"),
                            ("health", "Health Check"),
                        ],
                        help_text="API endpoint that was called",
                        max_length=50,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the API call was made",
                    ),
                ),
                (
                    "response_time_ms",
                    models.FloatField(
                        blank=True, help_text="Response time in milliseconds", null=True
                    ),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        blank=True, help_text="HTTP status code returned", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if the call failed",
                    ),
                ),
                (
                    "request_params",
                    models.JSONField(
                        blank=True,
                        help_text="Request parameters (for analysis)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Call Log",
                "verbose_name_plural": "API Call Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp", "endpoint"],
                        name="api_apicall_timesta_2ed4b3_idx",
                    )
                ],
            },
        ),
    ]
